# Generated by Django 4.2.8 on 2024-02-09 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0005_alter_algorithm_algorithm_file"),
        ("endpoints", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="endpoint",
            name="algorithm",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="algorithms.algorithm",
            ),
        ),
    ]
