# Generated by Django 4.2.8 on 2024-02-09 09:08

import algorithms.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0004_alter_algorithm_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="algorithm",
            name="algorithm_file",
            field=models.FileField(
                upload_to="algorithm_storage",
                validators=[algorithms.validators.validate_file_extension],
            ),
        ),
    ]
